
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 26 22:11:22 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 48;
  public static final int CONST = 7;
  public static final int NAMESPACE = 17;
  public static final int GEQUAL = 26;
  public static final int LPAREN = 40;
  public static final int GREATER = 25;
  public static final int SEMI = 34;
  public static final int CONTINUE = 15;
  public static final int FOR = 14;
  public static final int MINUS = 19;
  public static final int RPAREN = 41;
  public static final int STATIC = 16;
  public static final int AND = 29;
  public static final int EQUALTO = 23;
  public static final int OR = 30;
  public static final int COMMA = 36;
  public static final int CLASS = 10;
  public static final int INC = 32;
  public static final int MOV = 22;
  public static final int DIV = 21;
  public static final int LESSER = 27;
  public static final int PLUS = 18;
  public static final int IF = 8;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int EQUAL = 31;
  public static final int LAMBDA = 44;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int IDENT = 46;
  public static final int BREAK = 5;
  public static final int VOID = 12;
  public static final int COLON = 35;
  public static final int LBRACE = 38;
  public static final int ELSE = 6;
  public static final int LSQUARE = 42;
  public static final int LEQUAL = 28;
  public static final int READ = 11;
  public static final int RSQUARE = 43;
  public static final int NOTEQUALTO = 24;
  public static final int RBRACE = 39;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 49;
  public static final int DEC = 33;
  public static final int MAX = 45;
  public static final int PRINT = 3;
  public static final int NUMBER_CONST = 47;
}

